[package]
name = "keyboard-walker"
version = "0.3.3"
authors = ["Markus Eriksson <markus.eriksson.88@gmail.com>"]
edition = "2018"

[dependencies]
strum = "0.11.0"
strum_macros = "0.11.0"
quicli = "0.4"
structopt = "0.2.14"